-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 15:26:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` CHAR(8) NULL,
  `edad` VARCHAR(45) NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areas` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `relacion` INT NOT NULL,
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `areas_idarea` INT NOT NULL,
  PRIMARY KEY (`idcargo`),
  INDEX `fk_cargos_areas1_idx` (`areas_idarea` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos_empleado` (
  `idcargo_empleado` INT NOT NULL AUTO_INCREMENT,
  `idempleado` INT NOT NULL,
  `idcargo` INT NOT NULL,
  PRIMARY KEY (`idcargo_empleado`),
  INDEX `fk_cargos_empleado_empleados_idx` (`idempleado` ASC) ,
  INDEX `fk_cargos_empleado_cargos1_idx` (`idcargo` ASC))
ENGINE = InnoDB;
